# Generated by Django 5.1.2 on 2024-11-30 05:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passenger_count', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('round_trip', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(max_length=50)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('dest_image', models.URLField(blank=True, null=True)),
                ('destination1', models.CharField(blank=True, max_length=255, null=True)),
                ('destination2', models.CharField(blank=True, max_length=255, null=True)),
                ('transportation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('destination', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passenger_count', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(default='Not Specified', max_length=254)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_address', models.CharField(default='Not Specified', max_length=255)),
                ('dropoff_address', models.CharField(default='Not Specified', max_length=255)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('round_trip', models.BooleanField(default=False)),
                ('van', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='admin_app.van')),
            ],
        ),
    ]
