# Generated by Django 5.1.1 on 2024-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_address',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
