# Generated by Django 5.1.2 on 2024-12-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_remove_booking_dest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
