# Generated by Django 5.1.1 on 2024-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0003_booking_dropoff_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_van',
            field=models.CharField(default='driver1', max_length=255),
        ),
    ]
