# Generated by Django 5.1.1 on 2024-10-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_booking_driver_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
