# Generated by Django 5.1.2 on 2024-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombooking',
            name='custom_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=10),
        ),
    ]
