# Generated by Django 5.1.1 on 2024-10-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_booking_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='round_trip',
            field=models.BooleanField(default=False),
        ),
    ]
