# Generated by Django 5.1.1 on 2024-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0006_booking_round_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
