# Generated by Django 5.1.1 on 2024-10-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0008_remove_booking_driver_van_remove_booking_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='with_infant',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='with_pwd',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='with_senior',
        ),
    ]
