# Generated by Django 5.1.2 on 2024-10-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('customer_app', '0009_remove_booking_with_infant_remove_booking_with_pwd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='van',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='admin_app.van'),
        ),
    ]
