# Generated by Django 5.1.2 on 2024-10-30 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_destination'),
        ('customer_app', '0011_remove_booking_package_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_address',
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='admin_app.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CustomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('passenger_count', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('pickup_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_address', models.CharField(default='Not Specified', max_length=255)),
                ('dropoff_address', models.CharField(default='Not Specified', max_length=255)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('round_trip', models.BooleanField(default=False)),
                ('payment_mode', models.CharField(max_length=50)),
                ('proof_of_payment', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('van', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='admin_app.van')),
            ],
        ),
    ]
