# Generated by Django 5.1.2 on 2024-10-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0012_remove_booking_dropoff_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombooking',
            name='van',
        ),
        migrations.AddField(
            model_name='custombooking',
            name='package_price',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
    ]
