# Generated by Django 5.1.2 on 2024-11-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0014_custombooking_van'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='van',
        ),
    ]
