# Generated by Django 5.1.2 on 2024-11-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0015_remove_booking_van'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dest_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='destination2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='transportation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
