# Generated by Django 5.1.2 on 2024-11-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_van_package_price'),
        ('customer_app', '0016_booking_dest_image_booking_destination1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='admin_app.destination'),
        ),
    ]
