# Generated by Django 5.1.2 on 2024-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0017_alter_booking_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custombooking',
            name='package_price',
        ),
        migrations.RemoveField(
            model_name='custombooking',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='custombooking',
            name='proof_of_payment',
        ),
        migrations.AddField(
            model_name='custombooking',
            name='email_address',
            field=models.EmailField(default='Not Specified', max_length=254),
        ),
    ]
