# Generated by Django 5.1.2 on 2024-11-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.ImageField(upload_to='destination/')),
                ('destination1', models.CharField(max_length=100)),
                ('destination2', models.CharField(max_length=100)),
                ('transportationfee', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('file_upload', models.ImageField(default='N/A', upload_to='driver_images/')),
                ('name', models.CharField(max_length=100)),
                ('license', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.ImageField(upload_to='vans/')),
                ('model', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('is_company_van', models.BooleanField(default=False)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(default='Not defined')),
                ('engine', models.CharField(default='Not defined', max_length=50)),
                ('transmission', models.CharField(default='Not defined', max_length=50)),
                ('ac', models.CharField(default='Not defined', max_length=50)),
                ('entertainment', models.CharField(default='Not defined', max_length=50)),
                ('storage', models.TextField(default='Not defined')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.driver')),
            ],
        ),
        migrations.CreateModel(
            name='VanGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='van_gallery/')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='admin_app.van')),
            ],
        ),
    ]
