# Generated by Django 5.1.2 on 2024-11-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('forecasted_pax', models.IntegerField()),
                ('dynamic_price', models.FloatField()),
            ],
        ),
    ]
