# Generated by Django 5.1.2 on 2024-10-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='package_price',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
        ),
    ]
