# Generated by Django 5.1.1 on 2024-10-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_driver_license_alter_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('van_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='available', max_length=50)),
            ],
        ),
    ]
