# Generated by Django 5.1.2 on 2024-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_van_package_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.ImageField(upload_to='destination/')),
                ('destination1', models.CharField(max_length=100)),
                ('destination2', models.CharField(max_length=100)),
                ('transportationfee', models.DecimalField(decimal_places=2, default='0.0', max_digits=10)),
            ],
        ),
    ]
