# Generated by Django 5.1.2 on 2024-12-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_destination_base_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='transportationfee',
        ),
    ]
