# Generated by Django 5.1.2 on 2024-11-05 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='package_price',
        ),
    ]
