# Generated by Django 5.1.2 on 2024-12-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_destination_transportationfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
