# Generated by Django 5.1.2 on 2024-11-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_driver_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
