# Generated by Django 5.1.2 on 2024-11-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_driver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
