# Generated by Django 5.1.2 on 2024-11-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='ac',
            field=models.CharField(default='Not defined', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='description',
            field=models.TextField(default='Not defined'),
        ),
        migrations.AddField(
            model_name='van',
            name='engine',
            field=models.CharField(default='Not defined', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='entertainment',
            field=models.CharField(default='Not defined', max_length=50),
        ),
        migrations.AddField(
            model_name='van',
            name='storage',
            field=models.TextField(default='Not defined'),
        ),
        migrations.AddField(
            model_name='van',
            name='transmission',
            field=models.CharField(default='Not defined', max_length=50),
        ),
        migrations.CreateModel(
            name='VanGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='van_gallery/')),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='admin_app.van')),
            ],
        ),
    ]
